CREATE TABLE configuration_data (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	value varchar(255) not null
);

insert into configuration_data (name, value) values ('AccessToken', '01afd61e554fd26af02f328373b2ef591f40bc0c2f8cd907fad06bbd8b5b2080');
insert into configuration_data (name, value) values ('UUID', 'cb917723-29c3-4621-b6f9-ca66169b0389');

CREATE TABLE contact_to_deal (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	contact bigint not null,
	deal varchar(255) not null
);
